[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "tesseract-core"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.3"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.33"
